name: Lint YAML

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python version

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
